spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  cloud:
    aws:
      s3:
        region: ap-northeast-2 # 서울 리전
      credentials:
        access-key: AKIAXXXXXXXXXXXX  # IAM 액세스키
        secret-key: xxxxxxxxxxxxxxxxxxxx  # IAM 시크릿키


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fluxmall.domain.**.dto, com.fluxmall.domain.**.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-statement-timeout: 30

# JWT
jwt:
  access-token-expiration: 1800000    # 30분 (ms)
  refresh-token-expiration: 604800000 # 7일 (ms)


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

# Logging
logging:
  level:
    com.fluxmall: INFO
    org.springframework: WARN